calc(){ echo $(($@)) }

ej() { g++ -o ejec "$1" && ./ejec < in }
nin() {rm in && nano in}
nout(){ rm out && nano out }
gcom() { g++ -o ejec "$1" && ./ejec < in > output && (diff -w output out && echo "Correcto"); }