//Expresiones matematicas "5**5 | 7 & 8 - 54/3"
calc(){ echo $(($@)) }

//Solo ejecucion, impresion por STDOUT
ej() { g++ -o ejec "$1" && ./ejec < in }

//Nuevo in
nin() {rm in && nano in}
//Nuevo out
nout(){ rm out && nano out }

//Simulacion de un cph
gcom() { g++ -o ejec "$1" && ./ejec < in > output && (diff -w output out && echo "Correcto"); }